# This is a basic workflow to help you get started with Actions

name: Run refresh

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Install ssh keys  
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.craftytv }}
        name: id_rsa
        known_hosts: ${{ secrets.craftytv_known_hosts }}
    # Runs a set of commands using the runners shell
    - name: Pull, build and raise
      run: |
        ssh www@craftytv.perses.io,
        cd ~/video-chat,
        docker-compose -f docker-compose.yml down,
        git pull,
        docker-compose -f docker-compose.yml build,
        docker-compose -f docker-compose.yml up
        
